
services:

  postgis:
    container_name: postgis
    hostname: postgis
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: agwise_db
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - agwise-pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
      - web

  pgadmin:
      container_name: pgadmin
      hostname: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL:-pgadmin@munywele.co.ke}
        PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
        PGADMIN_CONFIG_SERVER_MODE: 'True'
        PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
        PGADMIN_CONFIG_LOGIN_BANNER: '"Authorised users only!"'
      volumes:
        - pg-admin:/var/lib/pgadmin

      ports:
        - "${PGADMIN_PORT:-5050}:80"
      networks:
        - web
        - internal
      restart: unless-stopped
      depends_on:
        - postgis

  agwise-potato:
    container_name: agwise-potato
    hostname: agwise-potato
    image: iita/agwise-potato-api:latest
    environment:
      FLASK_ENV: development
      DB_URL: ${AGWISE_DB_URL}
      LOG_LEVEL: ${AGWISE_LOG_LEVEL}
    restart: unless-stopped
    depends_on:
      - maria
    ports:
      - 5000:5000
    networks:
      - web
      - internal