name: "fuelrod-monitor"

services:
  monitor:
    hostname: beszel
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - 9699:8090
    volumes:
      - beszel-data:/beszel_data
    networks:
      - web



volumes:
  beszel-data:
    driver: local
    name: beszel-data