version: '3.3'

services:
  fuelrod-batch:
    container_name: fuelrod-batch
    image: tsobu/fuelrod-batch:${BATCH_VERSION}
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 9001:9001
    volumes:
      - ${PWD}/log:/log
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - BATCH_CRON=${BATCH_CRON}
    networks:
      - internal

volumes:
  data:

networks:
  internal:
    external: false
  web:
    external: true
