version: '3'

services:
  portainer:
      image: portainer/portainer-ce    
      container_name: portainer
      restart: always
      networks:
        - web
        - internal
      volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
          - portainer_data:/data
      ports:
      - '8010:8000'
      - '9010:9000'

# networks:
#   internal:
#     external: false
#   web:
#     external: true

volumes:
  portainer_data: {}
