[program:dramatiq-worker]
directory=/app/src
command=bash -c "dramatiq fuelrod_exporter.tasks --processes ${DRAMATIQ_PROCESSES:-1} --threads ${DRAMATIQ_THREADS:-2}"
autostart=true
autorestart=true
startretries=3
stdout_logfile=NONE
redirect_stderr=true
environment=DRAMATIQ_PROCESSES="1",DRAMATIQ_THREADS="2"