name: openproject

services:
  openproject:
    image: openproject/openproject:16
    container_name: openproject
    hostname: openproject
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      OPENPROJECT_SECRET_KEY_BASE: ${OPENPROJECT_SECRET_KEY_BASE:-changemeplz1234567890}
      # DATABASE_URL: ${OPENPROJECT_DB:?}
      OPENPROJECT_HOST__NAME: ${OPENPROJECT_HOST:-localhost:8080}
      OPENPROJECT_HTTPS: ${OPENPROJECT_HTTPS:-true}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - openproject_data:/var/openproject/assets
    networks:
      - web
      - internal

volumes:
  openproject_data:
      driver: local
      name: openproject-data
