name: "metabase"

services:
  metabase:
    container_name: metabase
    hostname: metabase
    image: metabase/metabase
    restart: unless-stopped
    ports:
      - 3006:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: ${DB_PORT:-3306}
      MB_DB_USER: ${DB_USERNAME}
      MB_DB_PASS: ${DB_PASSWORD}
      MB_DB_HOST: maria
    volumes:
      - metabase-data:/metabase-data
    networks:
      - web
      - internal
