services:
  dozzle:
    container_name: dozzle
    hostname: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    networks:
      - web
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_HOSTNAME:  ${DOZZLE_HOSTNAME}
    ports:
      - "9999:8080"

  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - 9999:8090
    volumes:
      - beszel-data:/beszel_data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600



volumes:
  beszel-data:
    driver: local
    name: beszel-data