name: "fuelrod"

services:

  minio1:
    image: minio/minio:${MINIO_TAG:-RELEASE.2024-03-26T22-10-45Z}
    container_name: minio1
    hostname: minio1
    restart: unless-stopped
    ports:
      - '9005:9000' #SERVER
      - '9006:9001' #UI
    volumes:
      - 'minio_data:/data'
    networks:
      - web
      - internal
    command: server http://minio{1...2}/data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-fuelrod}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS:-fuelrod}
      MINIO_SCHEME: ${MINIO_SCHEME:-http}
      MINIO_UPDATE: ${MINIO_UPDATE:-off}
      MINIO_PROMETHEUS_AUTH_TYPE: ${MINIO_PROMETHEUS_AUTH_TYPE:-public}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:-http://minio1:9000}
  minio2:
    image: minio/minio:${MINIO_TAG:-RELEASE.2024-03-26T22-10-45Z}
    container_name: minio2
    hostname: minio2
    volumes:
      - minio2_data:/data
    networks:
      - internal
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-fuelrod}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS:-fuelrod}
      MINIO_SCHEME: ${MINIO_SCHEME:-http}
      MINIO_UPDATE: ${MINIO_UPDATE:-off}
      MINIO_PROMETHEUS_AUTH_TYPE: ${MINIO_PROMETHEUS_AUTH_TYPE:-public}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:-http://minio2:9000}

    command: server http://minio{1...2}/data --console-address ":9001"

volumes:
  minio_data:
    name: minio_data
    driver: local
  minio2_data:
    name: minio2_data
    driver: local