services:
  dozzle:
    container_name: dozzle
    hostname: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    networks:
      - web
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_HOSTNAME:  ${DOZZLE_HOSTNAME}
    ports:
      - 9999:8080

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600

  newrelic:
    image: masgeek/new-relic-logger:${NEW_RELIC_TAG:-latest}
    container_name: newrelic
    hostname: newrelic
    cap_add:
      - SYS_PTRACE
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    environment:
      NRIA_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY:?}
    networks:
      - web
      - internal