name: 'mantisbt'

services:

  mantis:
      image: xlrl/mantisbt:latest
      container_name: mantis
      hostname: mantis
      environment:
          MANTIS_TIMEZONE: UTC
          MANTIS_ENABLE_ADMIN: 1
      volumes:
          - ./config:/var/www/html/config
          - ./custom:/var/www/html/custom
      restart: always
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.mantis.rule=Host(`${MANTIS_DOMAIN}`)"
          - "traefik.http.routers.mantis.entrypoints=https"
          - "traefik.http.routers.mantis.tls=true"
          - "traefik.http.routers.mantis.tls.certresolver=letsencrypt"
          - "traefik.http.services.mantis.loadbalancer.server.port=80"
      networks:
          - coolify
          - internal
