services:
  postgis:
    container_name: postgis
    hostname: postgis
    image: postgis/postgis:17-3.4
    environment:
      POSTGRES_DB: agwise_db
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
    - agwise-pg:/var/lib/postgresql/data
    networks:
      - internal