version: "3.8"

name: "fuelrod"

services:

  minio:
    image: minio/minio:${MINIO_TAG:-RELEASE.2024-03-26T22-10-45Z}
    container_name: minio
    hostname: minio
    restart: unless-stopped
    ports:
      - '9005:9000' # API
      - '9006:9001' # Console
    volumes:
      - minio_data:/data
    networks:
      - web
      - internal

    command: server /data --console-address ":9001"
    environment:
      MINIO_STORAGE_CLASS_STANDARD: ${MINIO_STORAGE_CLASS_STANDARD:-EC:0}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-fuelrod}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS:-fuelrod}
      MINIO_SCHEME: ${MINIO_SCHEME:-http}
      MINIO_UPDATE: ${MINIO_UPDATE:-off}
      MINIO_PROMETHEUS_AUTH_TYPE: ${MINIO_PROMETHEUS_AUTH_TYPE:-public}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:-http://minio:9000}
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  minio_data:
    name: minio_data
    driver: local