services:
  agwise-potato:
    container_name: agwise-potato
    hostname: agwise-potato
    image: iita/agwise-potato-api:latest
    environment:
      FLASK_ENV: development
      DB_URL: ${AGWISE_DB_URL}
      LOG_LEVEL: ${AGWISE_LOG_LEVEL}
    restart: unless-stopped
    depends_on:
      - maria
    ports:
      - 5000:5000
    networks:
      - web
      - internal