services:
  redis-admin:
    image: redis/redisinsight:latest
    container_name: redis-admin
    hostname: redis-admin
    restart: unless-stopped
    volumes:
      - redis-insight:/data
    ports:
      - "8081:5540"

    networks:
      - internal
      - web