services:
  agwise-potato:
    container_name: agwise-potato
    hostname: agwise-potato
    image: iita/agwise-potato-api:latest
    environment:
      FLASK_ENV: development
      DB_URL: ${AGWISE_DB_URL}
      LOG_LEVEL: ${AGWISE_LOG_LEVEL}
    restart: unless-stopped
    depends_on:
      - maria
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agwise.rule=Host(`${AGWISE_DOMAIN}`)"
      - "traefik.http.routers.agwise.entrypoints=https"
      - "traefik.http.routers.agwise.tls=true"
      - "traefik.http.routers.agwise.tls.certresolver=letsencrypt"
      - "traefik.http.services.agwise.loadbalancer.server.port=5000"
    networks:
      - coolify
      - internal
