services:
  cache:
    image: redis:8.4.0
    container_name: redis
    hostname: cache
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "6381:6379"
    env_file:
      - ../../.env
      - ../../.env-fuelrod
      - ../../.env-akilimo
    volumes:
      - redis-data:/data
    networks:
      - internal
      - web
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
    healthcheck:
      #test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      test: ["CMD", "redis-cli", "-a", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s