version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql
    hostname: mssql
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA:-Y}
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: ${MSSQL_PID:-Express}
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
    driver: local
    name: mssql-data
