name: "fuelrod"

services:

  exporter:
    container_name: exporter
    hostname: exporter
    image: masgeek/fuelrod-exporter-api:${EXPORTER_TAG:?EXPORTER_TAG must be set}
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ../../log/exporter:/app/logs

    env_file:
      - ../../.env
      - ../../.env-fuelrod
    environment:
      FLASK_DEBUG: ${FLASK_DEBUG:-0}
      SCHEDULER_ENABLED: ${SCHEDULER_ENABLED:-true}
      SCHEDULER_API_ENABLED: ${SCHEDULER_API_ENABLED:-true}
      SCHEDULER_INTERVAL: ${SCHEDULER_INTERVAL:-24h}
      EXPORT_MAX_AGE: ${EXPORT_MAX_AGE:-60d}
    networks:
      - web
      - internal


  worker:
    container_name: worker
    hostname: worker
    restart: no
    image: masgeek/fuelrod-exporter-worker:${EXPORTER_TAG:?EXPORTER_TAG must be set}
    volumes:
      - ../../log/worker:/app/logs
      - ../../config/supervisor/fuelrod-exporter:/etc/supervisor/conf.d
    env_file:
      - ../../.env
      - ../../.env-fuelrod
    depends_on:
      exporter:
          condition: service_started
    # environment:
    #   CONFIG_ENV: ${CONFIG_ENV:-prod}
    #   REDIS_URL: ${REDIS_URL:-redis://cache:6379/0}
    networks:
      - web
      - internal