services:
  dozzle:
    container_name: dozzle
    hostname: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    networks:
      - coolify
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_HOSTNAME: 'munywele.co.ke'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`${DOZZLE_DOMAIN}`)"
      - "traefik.http.routers.dozzle.entrypoints=https"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.tls.certresolver=letsencrypt"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

  drone:
    container_name: drone
    hostname: drone
    image: drone/drone:2
    restart: always
    volumes:
      - drone-ci:/var/lib/drone
    environment:
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=https
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drone.rule=Host(`${DRONE_DOMAIN}`)"
      - "traefik.http.routers.drone.entrypoints=https"
      - "traefik.http.routers.drone.tls=true"
      - "traefik.http.routers.drone.tls.certresolver=letsencrypt"
      - "traefik.http.services.drone.loadbalancer.server.port=80"
    networks:
      - coolify
      - internal

  drone-runner:
    hostname: drone-runner
    container_name: drone-runner
    image: drone/drone-runner-docker:1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - drone-ci:/var/lib/drone
    environment:
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_HOST=${DRONE_RPC_HOST}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=${DRONE_RUNNER_CAPACITY}
      - DRONE_RUNNER_NAME=${DRONE_RUNNER_NAME}
    networks:
      - internal
    depends_on:
      - drone
