services:
  postgres:
    image: postgres:17
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-fuelrod}
    networks:
      - internal
      - web
    ports:
      - "5432:5432"
    volumes:
      - pgdata-main:/var/lib/postgresql/data
      - ./init/pgsql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata-main:
    driver: local
    name: pgdata-main