version: '3.1'
name: "fuelrod"

services:
  metabase:
    container_name: metabase
    hostname: metabase
    image: metabase/metabase
    restart: unless-stopped
    ports:
      - 3006:3000
    volumes:
      - metabase-data:/metabase-data
    networks:
      - web
      - internal
