name: portainer

services:
  portainer:
    image: portainer/portainer-ce:2.37.0
    hostname: portainer
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9005:9000"   # UI
      - "9443:9443"   # optional HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    name: portainer
    driver: local
