name: "fuelrod"

services:

  minio:
    image: minio/minio:${MINIO_TAG:-RELEASE.2024-03-26T22-10-45Z}
    container_name: minio
    hostname: minio
    restart: no
    ports:
      - '9000:9000' #SERVER
      - '9001:9001' #UI
    volumes:
      - 'minio_data:/data'
    networks:
      - web
      - internal
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-fuelrod}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS:-fuelrod}
      MINIO_SCHEME: ${MINIO_SCHEME:-http}
      MINIO_UPDATE: ${MINIO_UPDATE:-off}
      MINIO_PROMETHEUS_AUTH_TYPE: ${MINIO_PROMETHEUS_AUTH_TYPE:-public}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:-http://minio:9000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    # depends_on:
    #   fuelrod:
    #       condition: service_healthy
    #   exporter:
    #       condition: service_started
          
volumes:
  minio_data:
    name: minio_data
    driver: local