services:
  watchtower:
    container_name: watchtower
    image: jakowenko/watchtower
    restart: unless-stopped
    pull_policy: always
    environment:
      PRUNE_IMAGES: 'true'
      PRUNE_VOLUMES: 'true'
      AUTO_UPDATE: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro