; Laravel Queue Workers Configuration
; Organized by priority and function

; This configuration manages Laravel queue workers, grouping them by function and priority.
; Each queue handles specific tasks crucial to the application's workflow.

; - SMS Update Queue: Updates SMS delivery status.
; - SMS Archiving Queue: Archives sent SMS messages for future reference or auditing.

; SMS Update Queue (Priority 225) - Handles SMS delivery status updates from the `sms-update` queue
[program:sync-data]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/html/fuelrod
command=php artisan queue:work --queue=sync --sleep=%(ENV_QUEUE_SLEEP)s --tries=%(ENV_QUEUE_MAX_TRIES)s --timeout=%(ENV_QUEUE_TIMEOUT)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
;numprocs=%(ENV_QUEUE_WORKERS)s
numprocs=1
stdout_logfile=/var/log/supervisor/laravel-data-sync.log
stderr_logfile=/var/log/supervisor/laravel-data-sync-error.log
stopwaitsecs=%(ENV_QUEUE_TIMEOUT)s
priority=225
inherit=defaults

[program:post-payment]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/html/fuelrod
command=php artisan queue:work --queue=payment --sleep=%(ENV_QUEUE_SLEEP)s --tries=%(ENV_QUEUE_MAX_TRIES)s --timeout=%(ENV_QUEUE_TIMEOUT)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=%(ENV_QUEUE_HEAVY_WORKERS)s
stdout_logfile=/var/log/supervisor/laravel-sms-chunk-update.log
stderr_logfile=/var/log/supervisor/laravel-sms-chunk-update-error.log
stopwaitsecs=%(ENV_QUEUE_TIMEOUT)s
priority=225
inherit=defaults