[program:laravel-link]
directory=/var/www/html/fuelrod
command=bash -c "php artisan storage:unlink && php artisan storage:link"  # Ensure both unlink and link run sequentially
stdout_logfile=/var/log/supervisor/laravel-link.log
# stderr_logfile=/var/log/supervisor/laravel-link-err.log
redirect_stderr=true
inherit=defaults
startsecs=0
priority=1

[program:clear-logs]
directory=/var/www/html/fuelrod
command=bash -c "rm -f storage/logs/*.log"
stdout_logfile=/var/log/supervisor/clear-logs.log
redirect_stderr=true
startsecs=15
priority=99
autostart=true
autorestart=false