[program:laravel-link]
directory=/var/www/html/fuelrod
command=bash -c "php artisan storage:unlink && php artisan storage:link"  # Ensure both unlink and link run sequentially
stdout_logfile=NONE
redirect_stderr=true
autostart=true
autorestart=true
startsecs=0
priority=1
inherit=defaults
