[program:post-payment]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/html/fuelrod
command=php artisan queue:work --queue=payment --sleep=%(ENV_QUEUE_SLEEP)s --tries=%(ENV_QUEUE_MAX_TRIES)s --timeout=%(ENV_QUEUE_TIMEOUT)s
autostart=QUEUE_ENABLED=%(ENV_AUTOSTART_OPTIMIZE)s
autorestart=false
stopasgroup=true
killasgroup=true
numprocs=%(ENV_QUEUE_HEAVY_WORKERS)s
stdout_logfile=/var/log/supervisor/laravel-sms-chunk-update.log
stderr_logfile=/var/log/supervisor/laravel-sms-chunk-update-error.log
stopwaitsecs=%(ENV_QUEUE_TIMEOUT)s
priority=225
inherit=defaults