[program:post-payments]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/html/fuelrod
command=php artisan queue:work --queue=payments --sleep=%(ENV_QUEUE_SLEEP)s --tries=%(ENV_QUEUE_MAX_TRIES)s --timeout=%(ENV_QUEUE_TIMEOUT)s
autostart=%(ENV_QUEUE_ENABLED)s
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=%(ENV_QUEUE_HEAVY_WORKERS)s
stdout_logfile=NONE
redirect_stderr=true
stopwaitsecs=%(ENV_QUEUE_TIMEOUT)s
priority=50
inherit=defaults