server:
  log_level: info

loki:
  positions_directory: /var/lib/grafana-agent/positions

  configs:
    - name: default

      clients:
        - url: ${LOKI_URL:-http://loki:3100}/loki/api/v1/push
          batchwait: 1s
          batchsize: 1048576
          backoff_config:
            min_period: 500ms
            max_period: 5m
            max_retries: 20
          external_labels:
            environment: production
            stack: fuelrod

      # scrape_configs:
      #   - job_name: supervisor-logs
      #     static_configs:
      #       - targets:
      #           - localhost
      #         labels:
      #           job: ${JOB_NAME:-fuelrod}
      #           instance: ${INSTANCE:-grafana-agent}
      #           host: ${HOST:-unknown}
      #           app: fuelrod
      #           component: supervisor
      #           __path__: /var/log/supervisor/*.log

metrics:
  configs:
    - name: default

      scrape_configs:
        - job_name: agent
          static_configs:
            - targets:
                - 127.0.0.1:12345

      remote_write:
        - url: http://prometheus:9090/api/v1/write