apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false
  
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
  
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}   # e.g. postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      postgresVersion: 15
      sslmode: ${POSTGRES_SSLMODE}           # disable, require, verify-full, etc.
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    isDefault: false
    editable: false

  
  - name: Redis
    type: redis-datasource
    access: proxy
    url: ${REDIS_HOST:-cache}:${REDIS_PORT:-6379}
    jsonData:
      client: ${REDIS_CLIENT:-standalone}
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    secureJsonData:
      password: ${REDIS_PASSWORD:-}
    isDefault: false
    editable: false