# WARNING
# wal_compression = lz4 requires PostgreSQL
# to be compiled with --with-lz4

# DB Version: 17
# OS Type: linux
# DB Type: mixed
# Total Memory (RAM): 4 GB
# CPUs num: 2
# Data Storage: ssd

# https://pgtune.leopard.in.ua/?dbVersion=17&osType=linux&dbType=mixed&cpuNum=2&totalMemory=4&totalMemoryUnit=GB&connectionNum=&hdType=ssd&dbSize=mid_ram
listen_addresses = '*'
max_connections = 100
shared_buffers = 1GB
effective_cache_size = 3GB
maintenance_work_mem = 256MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 4854kB
huge_pages = off
jit = off
wal_compression = lz4
min_wal_size = 1GB
max_wal_size = 4GB