-- CREATE ROLE fuelrod WITH LOGIN PASSWORD 'fuelrod';
ALTER ROLE fuelrod WITH SUPERUSER CREATEDB CREATEROLE REPLICATION;

-- CREATE DATABASE fuelrod OWNER fuelrod;

CREATE DATABASE shirakalu OWNER fuelrod;