[program:laravel-link]
directory=/var/www/html/akilimo
command=bash -c "php artisan storage:unlink && php artisan storage:link"  # Ensure both unlink and link run sequentially
stdout_logfile=NONE
redirect_stderr=true
inherit=defaults
startsecs=0
priority=1