[program:laravel-link]
directory=/var/www/html/fuelrod
command=bash -c "php artisan storage:unlink && php artisan storage:link"
stdout_logfile=/var/log/supervisor/laravel-link.log
redirect_stderr=true
inherit=defaults
startsecs=0
priority=1
