[program:laravel-link]
directory=/var/www/html/fuelrod
command=bash -c "php artisan storage:unlink && php artisan storage:link"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
inherit=defaults
startsecs=0
priority=1
