[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
stdout_logfile=/var/log/supervisor/php-fpm-out.log
stderr_logfile=/var/log/supervisor/php-fpm-err.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=3
redirect_stderr=false
priority=10
inherit=defaults
