events {}

http {
  ## Upstreams
  upstream minio_api {
    least_conn;
    server minio:9000;
  }

  upstream minio_console {
    least_conn;
    server minio:9001;
  }

  ## API (S3 access)
  server {
    listen 80;
    server_name files.akilimo.org;

    access_log /home/akilimo/logs/file-access.log;
    error_log  /home/akilimo/logs/file-error.log;

    location / {
      proxy_pass http://minio_api;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }

  ## Console (management UI)
  server {
    listen 81;
    server_name files.akilimo.org;

    access_log /home/akilimo/logs/console-access.log;
    error_log  /home/akilimo/logs/console-error.log;

    location / {
      proxy_pass http://minio_console;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
