[program:laravel-scheduler]
inherit=defaults
process_name=%(program_name)s_%(process_num)02d
command=/etc/scheduler/laravel-scheduler.sh
autostart=true
autorestart=true
numprocs=1
stdout_logfile=NONE
redirect_stderr=true
stopwaitsecs=60
stopasgroup=true
killasgroup=true