[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
stdout_logfile=/var/log/supervisor/php-fpm-out.log   ; write stdout to this file
stdout_logfile_maxbytes=50MB                           ; optional, max log size before rotation
stdout_logfile_backups=3                               ; optional, keep 3 rotated logs
stderr_logfile=/var/log/supervisor/php-fpm-err.log    ; write stderr to this file
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=3
redirect_stderr=false                                  ; keep stdout/stderr separate
priority=10
inherit=defaults
