name: Create next release
on:
  push:
    branches:
      - develop
jobs:
  next-release-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Next release'
          reviewer: ${{ github.actor }}
          assignee: ${{ github.actor }}
          target_branch: main
          label: release
          old_string: "**Write you description here**"
          body: "${{ github.event.head_commit.message }}"
          new_string: "${{ github.event.head_commit.message }}"
          get_diff: false
