name: Auto Approve
on: pull_request_target
jobs:
  pr-auto-approve:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    concurrency:
      cancel-in-progress: true
      group: pr-${{ github.ref }}
    if: github.actor != 'masgeek'
    steps:
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved automated PR"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
